### ISSUE TITLE
Shipwright logos added to CDF logos table

### ISSUE THREAD

**Issue by MarckK** [shipwright-io/community#102]
Hi,

Please add Shipwright logos to the [CDF logos table](https://github.com/cdfoundation/artwork#cdf-logos).

Having them there helps others quickly see and use the correct logos. 

Thank you!

**Comment by SaschaSchwarze0** [comment]
From grooming: we have all the icons. Adam volunteered to bring them to the CDF table.

**Comment by adambkaplan** [comment]
Artwork is updated on the CDF site: https://github.com/cdfoundation/artwork/pull/38

I'm going to submit a PR here so they are kept in sync.

**Comment by qu1queee** [comment]
From grooming, @adambkaplan anything left here?

**Comment by adambkaplan** [comment]
I think I (or someone else) should copy the files from cdfoundation/artwork and replace the files we currently have in the assets directory.

**Comment by SaschaSchwarze0** [comment]
Okay, I had assumed these are the same files anyway but just in a different folder structure. I synced it to the content and folder layout from cdfoundation. I did not find any reference to update in this repo. I hope there is no reference outside as well.
