### ISSUE TITLE
September 12th, 2022 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#104]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by adambkaplan** [comment]
Hacktoberfest: https://hacktoberfest.com/

**Comment by adambkaplan** [comment]
Announcement: Shipwright v0.11.0! https://shipwright.io/blog/2022/09/09/shipwright-v0.11.0-is-here/

**Comment by adambkaplan** [comment]
Minutes:

- Hacktoberfest - Adam can check event kit for anything we need to do to participate. Next grooming/refinement call - review good first issues.

**Comment by adambkaplan** [comment]
Update on Hacktoberfest - the main things we need to are the following:

- Add the “hacktoberfest” topic to your repository to OPT-IN TO HACKTOBERFEST and indicate you’re looking for contributions.
- Apply the “hacktoberfest” label to issues you want contributors to help with. Choose issues that have a well-defined scope and are self-contained.
- Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
- Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

Full guideline for maintainers is here: https://hacktoberfest.com/participation/#maintainers
