### ISSUE TITLE
Discussion: Update our motto / mission statement

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#111]
# Discussion Topic

When we launched Shipwright ~1.5 years ago, we started with a simple motto - "A framework for building container images on Kubernetes." One thing that stood out to me after our Beta API workshop is that we have aspirations that go beyond just building a container image. The Triggers and Image projects are expressions of that aspiration - we want to integrate with other cloud-native projects and build tooling that helps manage the deployment of cloud-native applications. The managed-push feature in the core Build project opens avenues to improve the app build experience - particularly when it comes to supporting features related to software supply chain security. Our current motto does not capture these goals, aspirations, and possibilities.

## Initial Proposal

"Shipwright: Build applications for the cloud, on the cloud"

## Next Steps

I'd like use to circulate/iterate on a new motto here - or even discuss if we should keep the current motto. Whatever we decide upon should be reflected on the website.

**Comment by SaschaSchwarze0** [comment]
For me, the container image is our central element and I would suggest to retain it in the mission statement. An application goes beyond that and also needs deployment artifacts.

A Cloud for me has the touch of a hosted service and we'll in a foreseeable future will not have an as-a-service shipwright somewhere I think (at least not maintained by Shipwright itself). Which could be what is expected by "on the cloud". In general, I think that Kubernetes is still a very strong buzzword that is clearer as cloud is.

What I am all for is to extend the list of verbs. Not just building container images, but also maintaining, maybe securing could be additions.

**Comment by qu1queee** [comment]
From Refinement, closing, nothing to do here.
