### ISSUE TITLE
Invitation of thelinuxfoundation to GitHub Shipwright org

### ISSUE THREAD

**Issue by fdegir** [shipwright-io/community#113]
In order for CD Foundation to support the project properly and make insights available for the project on LFX, the user thelinuxfoundation must be invited to the GitHub Shipwright Organization.

Please invite the user thelinuxfoundation as an owner at the organization level (not per repository) to the GitHub organization to start the process of including the project on LFX Insights.

**Comment by SaschaSchwarze0** [comment]
Done @fdegir

**Comment by fdegir** [comment]
Thanks @SaschaSchwarze0. I confirm LFX turned green now. Will get back a new issue if things don't work as expected.
