### ISSUE TITLE
December 5th, 2022 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#118]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by adambkaplan** [comment]
CDF Outreach Committee

**Comment by adambkaplan** [comment]
Minutes:

- CDF Outreach committee - first meeting is next week (December 14th, 10:30AM-11:30AM EST). This is a way for projects to engage with CDF on matters like infrastructure, project governance, project marketing/awareness, and events. Meetings will be held monthly until cdCon (May), then every other month afterwards. This is a great opportunity for contributors to get more involved with the CDF!
