### ISSUE TITLE
December 12, 2022 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#119]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by qu1queee** [comment]
Meeting minutes:

- @otaviof custom tasks support. PR is open and needs feedback, see  https://github.com/shipwright-io/triggers/pull/12

- @otaviof we need to be able to push component images from shipwright-io/triggers to the same registry as shipwright-io/build

- @qu1queee to participate on the Outreach Committee for the CD Foundation representing SHP.

- from @SaschaSchwarze0 , PR on manage-push is ready to review https://github.com/shipwright-io/build/pull/1046 , see [EP](https://github.com/shipwright-io/community/blob/main/ships/0026-shipwright-managed-push.md)
