### ISSUE TITLE
April 17th, 2023 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#134]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by qu1queee** [comment]
- Docker support for OS project, status.
- Ongoing v1beta1 migration
- Review on https://github.com/shipwright-io/cli/pull/180 (help wanted)
- CDF
   - https://devstats.cd.foundation
   - https://github.com/cdfoundation/wg-lfx-requirements
   - Possibility to have a new voting member in the TOC seat, as Shipwright Project representative
- CDCon 2023
  - We should have a blog post
  - Need of a release
  - Who is going?
  - Schedule Open Slots

🐖

**Comment by jitendar-singh** [comment]
**Testing openshift build v2**

Today the shipwright build controller project is strongly covered by e2e tests.These e2e tests are running on a kind cluster.

As part of Openshift Builds productization, we would like to ensure test coverage on openshift. We have identified two test approaches that we would like to discuss for productization.


Approach 1

Running existing upstream e2e tests on Openshift
We will have to Configure openshift CI to run the test already present upstream.

needs discussion with the community to run tests on openshift CI against each PR OR fork upstream and do run the ci-bot on a downstream project under Openshift github organization
needs test to be adapted(compatible with openshift as currently they run on KIND)
Effort involved is unknown

Approach 2

Run QA test to Qualify releases based on artifact provided by CPaaS builds and brew

These are E2E tests to QA the whole chain:
operator installation, 
build controller, 
Side image used by Openshift Builds like Git-clone, Image-bundler, and also specific 
Rbac for openshift
Define a set of feature that need to be tested for the GA(Needs sync with [Siamak Sadeghianfar](mailto:ssadeghi@redhat.com))
We already have a framework for it
Use UMB to automate the triggering of test via CPaaS: this needs to set up an infrastructure for this CI (Other project like pipelines are using this approach)
