### ISSUE TITLE
Enable Pull Request Size GiHub App

### ISSUE THREAD

**Issue by coreydaley** [shipwright-io/community#151]
Install/configure https://github.com/marketplace/pull-request-size/ for the shipwright-io organization.

**Comment by SaschaSchwarze0** [comment]
I enabled it. It seems that it does not add the labels to existing pull requests. At least not immediately. Let's wait for the first label(s) to appear. Then, we can close this.

**Comment by coreydaley** [comment]
It sized this pull request: https://github.com/shipwright-io/operator/pull/138
