### ISSUE TITLE
Enable CodeQL scanning on all repositories

### ISSUE THREAD

**Issue by coreydaley** [shipwright-io/community#153]
Must be completed by an admin

Instructions: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-default-setup-for-code-scanning

**Comment by coreydaley** [comment]
Since we have been running the trial on shipwright-io/build what do you all think of enabling it on the rest of the code repositories?

**Comment by SaschaSchwarze0** [comment]
Yes, I think I have observed enough in the meantime. What is not ideal is, that CodeQL only runs if there are really code changes. This means for example that we cannot declare CodeQL checks as required in the branch settings. But, so be it.

**Comment by coreydaley** [comment]
I think that it also runs periodically.

**Comment by SaschaSchwarze0** [comment]
This is done for build, cli, image, operator, triggers.
