### ISSUE TITLE
July 26th, 2021 Community Meeting

### ISSUE THREAD

**Issue by HeavyWombat** [shipwright-io/community#19]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by HeavyWombat** [comment]
Replace `Dockerfile` `FROM` images from DockerHub based images to Quay.io based images to reduce DockerHub Rate Limit issues.

![image](https://user-images.githubusercontent.com/1979133/126987864-c9c460d1-190d-4246-a4c7-f60bf016982b.png)

**Comment by otaviof** [comment]
Catch up on Local Source Upload EP (#11)

![image](https://user-images.githubusercontent.com/11710/126989056-6b853360-ebd5-4f47-b415-ff800f57a64d.png)

**Comment by gabemontero** [comment]
pruning (in light if RedHat SRE experiences with Tekton)
- Tekton Results
- current feature for tracking:  https://github.com/shipwright-io/build/issues/53
- fancier ideas like additional controllers that monitor etcd prometheus alerts and adjust "system settings" accordingly

**Comment by SaschaSchwarze0** [comment]
[OWNERS](https://github.com/shipwright-io/community/blob/main/OWNERS) in community repo is quite empty.

**Comment by imjasonh** [comment]
CDF stuff:
- podcast recording next Monday (any other volunteers?)
- CDF blog post + marketing push next week, prime your retweet buttons
