### ISSUE TITLE
March 5th, 2024 Community Meeting

### ISSUE THREAD

**Issue by HeavyWombat** [shipwright-io/community#193]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by HeavyWombat** [comment]
It's been a year since the last update to the Shipwright Build [`OWNERS` file](https://github.com/shipwright-io/build/blob/main/OWNERS) and I would suggest to review the list.

**Comment by adambkaplan** [comment]
Shipwright Most Valuable Contributor Nomination

**Comment by qu1queee** [comment]
Meeting minutes:

- For the OWNER's file, to sync with people who might not longer be a good candidate for the list(approvers) before doing any changes. Also, consider to make use of the `emeritus` list. 
- To check dev stats(CDF stats site) for potential new approvers/reviewers. @qu1queee to do this.
- Shipwright Most Valuable Contributor Nomination decision -> @qu1queee .
- @karanibm6 requested help on the Vulscan PR.
