### ISSUE TITLE
April 8th, 2024 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#199]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by SaschaSchwarze0** [comment]
For PRs related to patch-releases, do we want to create a GitHub milestone, so that we can associate it ?

**Comment by adambkaplan** [comment]
Notes from TAG App-Delivery meeting
