### ISSUE TITLE
July 15, 2024 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#227]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by SaschaSchwarze0** [comment]
Pls review https://github.com/shipwright-io/build/pull/1645, fixes e2e failures that come in all PRs.

**Comment by adambkaplan** [comment]
Minutes:

- Build PR fixes EOL for buildpacks + NodeJS
- Tekton LTS
-- Staying on newest ensures vulnerabilities are patched.
-- Separate go module version + version of Tekton deployed?
-- Version skews of dependencies - a concern for Build as well as operator. Operator Lifecycle Manager originally had notions of automatic dependency resolution, Shipwright operator uses this. Proved more difficult in practice - may remove this feature in the future.
-- Decision: we will use newest LTS for Tekton (and bring in k8s version). After that lands, we can experiment using a matrix with next older Tekton + k8s deployed in PR testing.
-- Release process - LTS will mark a "feature freeze". After Tekton update merges, we start stabilizing for a release across CLI, Build, and Operator repos. Includes creation of release branches. Goal to release 30 days after Tekton release - may be challenging with summer vacations/availability.
- Blog post for vulnerability scanning feature drafted!
