### ISSUE TITLE
August 23rd Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#24]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal :smile_cat:

**Comment by adambkaplan** [comment]
Provisional SHIP - Build Strategy Volumes #23

**Comment by imjasonh** [comment]
Provisional SHIP - Image API: https://github.com/shipwright-io/community/pull/25

**Comment by imjasonh** [comment]
CDF AMA September 1

**Comment by adambkaplan** [comment]
Minutes:

- #23 - caching is one possible use case of volumes, but not the only use case. Needs to be identified in the SHIP.
- #25 - Image API coming from Red Hat folks who used to work directly with current RH Shipwright contributors. Desire to have Image API work independently of Builds (and similarly Builds work independently of Image).
- CDF AMA - @imjasonh to confirm date with CDF.

**Comment by qu1queee** [comment]
❤️️
