### ISSUE TITLE
September 13th, 2021 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#29]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal :smile_cat:

**Comment by adambkaplan** [comment]
SHIP-0021 - needs a non-Red Hat approver #11

**Comment by adambkaplan** [comment]
Discussion: Move grooming call to a different day?

**Comment by gabemontero** [comment]
"dependency magnets" - stemmed from exchange between myself and @HeavyWombat in https://github.com/shipwright-io/cli/pull/35

**Comment by adambkaplan** [comment]
- Frida
