### ISSUE TITLE
September 27th, 2021 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#31]
* Please add a topic in this thread and add a link to the Github issue associated with the topic.
* Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
* (optional) Paste the image of an animal :smile_cat:

**Comment by adambkaplan** [comment]
Testing private git repositories in PRs using https://github.com/shipwright-io/build/pull/849

**Comment by adambkaplan** [comment]
API review issue for builds - have we effectively replaced this with the SHIP process? https://github.com/shipwright-io/build/issues/516

**Comment by gabemontero** [comment]
more quay.io/shipwright image pruning ??

`quay.io/shipwright/mutate-image:latest`

Also, how does one get permission to even view https://quay.io/repository/shipwright ??

**Comment by imjasonh** [comment]
`ko` fix is https://github.com/google/ko/pull/448, but it's orthogonal to the image issue.

There's no image at `quay.io/shipwright`, so that's why that link 404s (for everyone, I assume). `quay.io/shipwright/mutate-image` does exist, and can be browed here: https://quay.io/repository/shipwright/mutate-image?tab=tags

**Comment by coreydaley** [comment]
@gabemontero I think what you want is https://quay.io/organization/shipwright

**Comment by gabemontero** [comment]
> @gabemontero I think what you want is https://quay.io/organization/shipwright

you are correct @coreydaley :-)

**Comment by adambkaplan** [comment]
Agenda item: participate in Hacktoberfest? https://hacktoberfest.digitalocean.com/

**Comment by adambkaplan** [comment]
Minutes:

- Git server PR - defer to next meeting.
- API review issue - we should close this issue for more focused issues. Any outstanding wants/discussion points should have a separate issue created.
- quay.io/shipwright/mutate-image doesn't have a `latest` tag. We update our nightly build to tag `latest` as well as `nightly`, however this can lead to complexities in generating the release. Will be discussed further in an issue.
- Hacktoberfest - we probably aren't ready to participate. A lot of changes are in flight, we don't have enough "good first issues" for new contributors.

**Comment by SaschaSchwarze0** [comment]
Issue about missing latest tag: https://github.com/shipwright-io/build/issues/877
