### ISSUE TITLE
October 4th, 2021 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#32]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal :smile_cat:

**Comment by otaviof** [comment]
#11 EP current status and open questions

![](https://upload.wikimedia.org/wikipedia/commons/9/9a/White-rumped_vulture_%28Gyps_bengalensis%29_Photograph_by_Shantanu_Kuveskar.jpg)

**Comment by gabemontero** [comment]
Notes:
- the crux around the https://github.com/shipwright-io/community/pull/11 discussion: how much presence do we start with in the first class API vs. annotations; how much of a mixture of API vs. annotations exists
- so nuanced, minor diffs; consensus among discussion participants not universal
- @sbose78 will chime in to the existing arguments currently carried by @otaviof @gabemontero @SaschaSchwarze0 
- @otaviof will consume @sbose78 's comments, perhaps make a final adjustment
- we'll merge the EP and get started with shipwright-io/build and shipwright-io/cli PRs, but with the awareness from everyone that continued discussion in those PRs, as well as the testing results, might result in required adjustment to the EP to reflect the more final landing spot
