### ISSUE TITLE
October 18, 2021 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#38]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by adambkaplan** [comment]
CII Best Practices #35

**Comment by imjasonh** [comment]
- Zoom for future community calls
  - public YouTube channel?
- #25 next steps
