### ISSUE TITLE
December 6, 2021 Community Meeting

### ISSUE THREAD

**Issue by HeavyWombat** [shipwright-io/community#45]
Please add a topic in this thread and add a link to the Github issue associated with the topic.
Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
(optional) Paste the image of an animal

**Comment by HeavyWombat** [comment]
Last release was two months ago. Is it time for a new release?

![image](https://user-images.githubusercontent.com/1979133/144855907-ae52753f-3a9c-4ac6-aaa6-383093a6878b.png)

**Comment by adambkaplan** [comment]
Minutes:

- Release timeframe was discussed for December 17th. https://lists.shipwright.io/archives/list/shipwright-dev@lists.shipwright.io/thread/WWEGOQ4W7SIBDODDCCAVHYHMCBVUIA6Q/
- Core release tasks
  - Build controller release. **Code freeze and release candidate December 9th**.
  - CLI rebase and release
  - Operator release - maybe?
  - Website - docs update
- @adambkaplan will create a Google Form for folks to sign up, post to Slack & mailing list.
- Reviewed outstanding issues on the shipwright-dev project board
