### ISSUE TITLE
December 13, 2021 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#46]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting
- (optional) Paste the image of an animal

**Comment by SaschaSchwarze0** [comment]
v0.7.0 release, CLI TODOs

**Comment by HeavyWombat** [comment]
Can we have a look at https://github.com/shipwright-io/build/pull/930?
![image](https://user-images.githubusercontent.com/1979133/145825942-d5f09037-898a-48d5-b91b-0859fc3413b9.png)

**Comment by SaschaSchwarze0** [comment]
CLI:

- Gabe is checking on the failing test, will go back to ignore the buildrun failure to get the feature in
- Tomorrow afternoon Germany time we should make a decision to build the CLI

Error results PR:

- Let's bump Adam

Christmas vacation coming soon, low coverage already next Monday
