### ISSUE TITLE
February 21st, 2022 Community Meeting

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/community#62]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by SaschaSchwarze0** [comment]
Suggesting a quick discission regarding one aspect of the [BuildRun cleanup ship](https://github.com/shipwright-io/community/pull/61).

Basically one will be able to define limits (how many BuildRuns for a Build) and TTLs (how long after a completion a BuildRun should stay) in a new retention section of the Build. Users can use both features on the same Build but likely scenario is to use one of the two approaches.

Question: what is the expected behavior of completed BuildRuns when the Build gets updated later.

Example 1:

1. Build defines a TTL after successful completion of six hours.
2. BuildRun completes at 1pm. Would be deleted at 7pm.
3. Build now gets updated and TTL is changed to four hours.

-> When should the BuildRun get deleted? At 5pm or 7pm.

-- 

Example 2:

1. Build defines a limit of five successful BuildRuns.
2. Five successfuly BuildRuns are in the system.
3. The limit is changed to four successful BuildRuns.

-> What should happen? Should the oldest successful BuildRun be immediatly deleted, or should the cleanup happen when the next BuildRun completes successfully?

-- 

Additional considerations:

* The BuildRun status contains the BuildSpec when the TaskRun was generated. This contains the old TTL/limit values.
* The BuildRun spec can override the TTL value from the Build.
* Limits apply to all BuildRuns of a Build. While there can be different limit values in the BuildRun status buildSpec, actually only one value can be applied.
* TTL applies to an individual BuildRun (= the amount of other BuildRuns of the same Build does not play a role). Theoretically one can honor different values.

```
|\---/|
| o_o |
 \_^_/
```

**Comment by SaschaSchwarze0** [comment]
I suggest we do a cleanup of aged pull requests together in the build repo. We can decide to keep some PRs open, close them but open an issue, or close them without an issue.

**Comment by qu1queee** [comment]
On https://github.com/shipwright-io/community/discussions/60 , upcoming proposal coming.

**Comment by ricardomaraschini** [comment]
Image repo QA
