### ISSUE TITLE
February 28, 2022 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#63]
* Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
* Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
* (optional) Paste the image of an animal :smile_cat:

**Comment by qu1queee** [comment]
- Feedback on [SHIP Lookout Runbook](https://docs.google.com/document/d/1EpG49DPzeNlUUnIpDL7YYk3a30frZWw0J2Qx88_Jm4Q/edit?usp=sharing)
