### ISSUE TITLE
March 7, 2022 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#65]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal :smile_cat:

**Comment by adambkaplan** [comment]
Validating Admission Webhook for Shipwright objects: https://github.com/shipwright-io/build/issues/596

**Comment by SaschaSchwarze0** [comment]
My proposal for the next releases:

- v0.9 "Easter release" in the week April 4th - 8th: we should be able to get some nice features wrapped up for the ships that were recently merged (buildrun cleanup, standalone buildrun)
- v0.10 "cdCon release" end of May in the week May 23rd to 27th.

🐻

**Comment by SaschaSchwarze0** [comment]
SHIPs that require a second approval from RedHat to get merged:

- [SHIP-0026: Introduce shipwright-managed push #53](https://github.com/shipwright-io/community/pull/53)
- [SHIP-0027: Image Abstraction Layer #57](https://github.com/shipwright-io/community/pull/57)

🐹
