### ISSUE TITLE
Discussion: Shipwright Image APIs

### ISSUE THREAD

**Issue by imjasonh** [shipwright-io/community#8]
Related: https://github.com/shipwright-io/cli/issues/3

Shipwright mainly deals with configuring and executing image _builds_ today, but doesn't have a first-class concept of _images_ in the API. Users can inspect BuildRuns for details of images they've built, but otherwise there's no concept of an "image" that wasn't built by Shipwright (e.g., `nginx` from DockerHub).

OpenShift has a number of resources related to images, e.g., ImageStream:
- https://docs.openshift.com/container-platform/4.7/openshift_images/image-streams-manage.html
- API docs: https://docs.openshift.com/container-platform/4.7/rest_api/image_apis/image-apis-index.html

These resources enable lots of use cases, such as:
- inspecting, managing and watching the tag history of an image using in-cluster CRD resources
- mutating requests for images-by-tag to replace them with immutable content-addressed references
- caching images in an in-cluster registry, and mutating requests for images to replace them with cached references (useful in airgapped scenarios)
- enforcing other image-related policies (require signatures, require image scans)

Shipwright is a natural place for the next version of this sort of resource, based on experience building OpenShift ImageStreams, but separate from the OpenShift platform.

This shouldn't involve implementing a full in-cluster container image registry, since there are already plenty options already in existence.

cc @sbose78 @adambkaplan @ricardomaraschini (similar to https://github.com/ricardomaraschini/tagger)

**Comment by sbose78** [comment]
+1 on this. A Kubernetes native abstraction of an Image feels extremely valuable.

**Comment by ricardomaraschini** [comment]
Going through this list and checking what is already implemented @ https://github.com/ricardomaraschini/tagger

> * inspecting, managing and watching the tag history of an image using in-cluster CRD resources

This is supported. When it comes to "inspect" we do not have yet the full image configuration exposed (image details such as number of layers, environment variables or exposed ports, etc).

> * mutating requests for images-by-tag to replace them with immutable content-addressed references

This is supported.

> * caching images in an in-cluster registry, and mutating requests for images to replace them with cached references (useful in airgapped scenarios)

This is supported.

> * enforcing other image-related policies (require signatures, require image scans)

This is an avenue that still needs to be covered.

**Comment by ricardomaraschini** [comment]
@imjasonh Is there something else we need to discuss on this issue? I think that now that https://github.com/shipwright-io/community/pull/57 is merged we can close it. WDYT ?
