### ISSUE TITLE
Shipwright buildrun issue

### ISSUE THREAD

**Issue by niskarsha10** [shipwright-io/community#95]
Shipwright build successfully worked. However, I am facing issue regarding build run. While describing the pod, no events are shown. I am following the official documentation of Shipwright from the link below: 

https://github.com/shipwright-io/build

<img width="969" alt="Screen Shot 2022-07-06 at 17 05 36" src="https://user-images.githubusercontent.com/99004410/177538836-4e99f4f7-b0bd-473e-a75b-453823ee9a32.png">

<img width="746" alt="Screen Shot 2022-07-06 at 17 06 03" src="https://user-images.githubusercontent.com/99004410/177538906-02e1bfc6-4708-4c88-bcb1-1a0869b8ef44.png">

<img width="1363" alt="Screen Shot 2022-07-06 at 17 06 39" src="https://user-images.githubusercontent.com/99004410/177539008-233254cd-d807-4325-89fc-b52d208222ac.png">

<img width="930" alt="Screen Shot 2022-07-06 at 17 09 02" src="https://user-images.githubusercontent.com/99004410/177539454-1decc41a-2ce0-4759-81dd-e3fc87e01136.png">

**Comment by SaschaSchwarze0** [comment]
@niskarsha10 Kubernetes clusters have a retention for events. The default is one hour. It can be configured using the `--event-ttl` flag on the Kubernetes API server. You can search for this flag here: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/.

Given your BuildRun is completed more than four hours ago, seeing no pod events is expected based on above.
